version: '3.4'

services:
  seagull-frontend:
    image: seagull-frontend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"